import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — TellySauce",
};

export default function TermsOfService() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-16 text-gray-300">
      <Link href="/" className="text-sm text-gray-500 hover:text-gray-300 transition mb-8 inline-block">
        ← Back to TellySauce
      </Link>

      <h1 className="text-3xl font-extrabold text-white mb-2">Terms of Service</h1>
      <p className="text-gray-500 text-sm mb-10">Last updated: April 2025</p>

      <Section title="About TellySauce">
        <p>
          TellySauce is a web application that lets you search for, rate, and
          get AI-powered recommendations for TV shows and films. It is operated
          by Andy Briggs (&ldquo;we&rdquo;, &ldquo;us&rdquo;, &ldquo;our&rdquo;), based in the United Kingdom.
        </p>
        <p className="mt-3">
          By using TellySauce you agree to these terms. If you do not agree,
          please do not use the service.
        </p>
      </Section>

      <Section title="Your account">
        <p>
          You sign in using your Google account. You are responsible for
          maintaining the security of your Google account. We are not liable for
          any loss or damage arising from unauthorised access to your account.
        </p>
      </Section>

      <Section title="Free tier and TellySauce Pro">
        <h3 className="font-semibold text-white mt-4 mb-1">Free tier</h3>
        <p>
          All users receive 3 free AI recommendation generations at no cost.
          Daily AI picks (curated popular titles) are always free and do not
          count toward this limit.
        </p>

        <h3 className="font-semibold text-white mt-4 mb-1">TellySauce Pro subscription</h3>
        <p>
          TellySauce Pro is priced at <strong className="text-white">£1.99 per month</strong> and
          provides unlimited AI recommendation generations. Billing is handled
          by Stripe and renews monthly on the date you subscribed.
        </p>

        <h3 className="font-semibold text-white mt-4 mb-1">Cancellation</h3>
        <p>
          You can cancel your subscription at any time via the &ldquo;Pro · Manage&rdquo;
          button in the app, which opens the Stripe billing portal. Cancellation
          takes effect at the end of the current billing period — you retain Pro
          access until then. We do not offer partial-month refunds.
        </p>

        <h3 className="font-semibold text-white mt-4 mb-1">Refunds</h3>
        <p>
          Under the UK Consumer Contracts Regulations, you have the right to
          cancel within 14 days of your first subscription purchase for a full
          refund, unless you have already used the Pro features during that
          period. To request a refund, contact us at{" "}
          <a href="mailto:andybriggs84@gmail.com" className="text-white underline hover:text-gray-200 transition">
            andybriggs84@gmail.com
          </a>.
        </p>
      </Section>

      <Section title="AI recommendations">
        <p>
          AI recommendations are generated by Google&apos;s Gemini AI and are
          provided for entertainment and discovery purposes only. We do not
          guarantee their accuracy, relevance, or completeness. Recommendations
          are not editorial endorsements.
        </p>
        <p className="mt-3">
          Recommendation results may be cached for up to 7 days. Generating new
          recommendations refreshes your results and counts toward your free
          generation limit (or uses your Pro subscription).
        </p>
      </Section>

      <Section title="Acceptable use">
        <p>You agree not to:</p>
        <ul className="mt-3 space-y-1 list-disc list-inside">
          <li>Use the service for any unlawful purpose</li>
          <li>Attempt to reverse-engineer, scrape, or abuse the service or its APIs</li>
          <li>Create multiple accounts to circumvent the free tier limits</li>
          <li>Interfere with the service&apos;s availability or performance</li>
        </ul>
        <p className="mt-3">
          We reserve the right to suspend or terminate accounts that violate
          these terms without notice.
        </p>
      </Section>

      <Section title="Intellectual property">
        <p>
          Title metadata, posters, and descriptions are provided by{" "}
          <a href="https://www.themoviedb.org" target="_blank" rel="noopener noreferrer" className="underline hover:text-white transition">
            The Movie Database (TMDB)
          </a>{" "}
          and are subject to their terms of use. TellySauce is not endorsed or
          certified by TMDB.
        </p>
        <p className="mt-3">
          The TellySauce application, branding, and original content are owned
          by us and may not be reproduced without permission.
        </p>
      </Section>

      <Section title="Limitation of liability">
        <p>
          TellySauce is provided &ldquo;as is&rdquo; without warranties of any kind. To the
          fullest extent permitted by law, we are not liable for any indirect,
          incidental, or consequential damages arising from your use of the
          service.
        </p>
        <p className="mt-3">
          Nothing in these terms limits your statutory rights as a UK consumer.
        </p>
      </Section>

      <Section title="Changes to these terms">
        <p>
          We may update these terms from time to time. Continued use of the
          service after changes are posted constitutes your acceptance of the
          updated terms. Material changes will be reflected with an updated date
          at the top of this page.
        </p>
      </Section>

      <Section title="Governing law">
        <p>
          These terms are governed by the laws of England and Wales. Any
          disputes shall be subject to the exclusive jurisdiction of the courts
          of England and Wales.
        </p>
      </Section>

      <Section title="Contact">
        <p>
          For any questions about these terms, contact us at{" "}
          <a href="mailto:andybriggs84@gmail.com" className="text-white underline hover:text-gray-200 transition">
            andybriggs84@gmail.com
          </a>.
        </p>
      </Section>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-10">
      <h2 className="text-xl font-bold text-white mb-3 pb-2 border-b border-white/10">{title}</h2>
      <div className="text-gray-300 leading-relaxed text-sm">{children}</div>
    </section>
  );
}
